name: helper
description: A new Flutter package.
version: 0.0.7
author: HaniHashemi <jhanihashemi@gmail.com>
homepage: https://github.com/hanihashemi/Helper

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: